name: "Kerosene"
description: "Firestarter's library of little bits and bobs that keep the server ticking."
main: "com.firestartermc.kerosene.Kerosene"
author: "TechToolbox (nkomarn)"
website: "https://firestartermc.com/opensource"
version: "5.0"
api-version: "1.16"

softdepend:
  - "Essentials"
  - "Vault"

commands:
  kerosene:
    description: "Base Kerosene management command."
    permission: "firestarter.admin"

permissions:
  firestarter.admin:
    default: op
    description: "Allow access to administrative features."
