name: Kerosene
version: 3.3
author: TechToolbox (@nkomarn)
main: xyz.nkomarn.Kerosene.Kerosene
description: Firestarter's library of little bits and bobs that keep the server ticking.
website: https://firestartermc.com/opensource
api-version: 1.16
depend: ['Essentials', 'GriefPrevention', 'Vault']

commands:
  kerosene:
    description: "Base Kerosene management command."
    permission: "firestarterm.admin"

permissions:
  firestarterm.admin:
    default: op
    description: "Allow access to administrative features."
  firestarter.vanish:
    default: op
    description: "Allow viewing of vanished players."
